codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default:
        # Don't fail PR if coverage drops slightly
        target: auto
        threshold: 5%
        paths:
          - "dayflow/"
    patch:
      default:
        # Require at least 80% coverage on new code
        target: 80%
        threshold: 10%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "tests/"
  - "examples/"
  - "docs/"
  - "setup.py"
  - "**/__init__.py"
